In [5]:
import numpy as np

In [12]:
board = np.arange(9).reshape(3,3)
board[:][:] = 0
player_list =[1,2]

In [13]:
def check_win(board, player):

    # Check rows
    for row in range(3):
        if all(board[row][col] == player for col in range(3)):
            return True

    # Check columns
    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True

    # Check diagonals (optional)
    if player == board[0][0] == board[1][1] == board[2][2]:
        return True
    if player == board[0][2] == board[1][1] == board[2][0]:
        return True

    return False

In [14]:
def main():
    a = 1

    while True:
        current_player = player_list[(a-1)%2]

        row = int(input(f'player {current_player}, enter row 1~3'))-1
        column = int(input(f'player {current_player}, enter column 1~3'))-1
        
        while board[row][column] !=0:
            print('invalid move. choose a different space')
            row = int(input(f'player {current_player}, enter row 1~3'))-1
            column = int(input(f'player {current_player}, enter column 1~3'))-1
        
        board[row][column] = current_player
        print(board)

        if check_win(board, current_player):
            print(f'player{current_player} wins!')
            break

        if all(cell !=0 for row in board for cell in row):
            print("it's a tie!")
            break

        a+=1

In [15]:
if __name__ == "__main__":
    main()

[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 2 0]
 [0 0 0]]
[[1 0 0]
 [0 2 0]
 [0 0 1]]
[[1 2 0]
 [0 2 0]
 [0 0 1]]
[[1 2 0]
 [0 2 0]
 [0 1 1]]
[[1 2 0]
 [0 2 0]
 [2 1 1]]
[[1 2 1]
 [0 2 0]
 [2 1 1]]
[[1 2 1]
 [2 2 0]
 [2 1 1]]
[[1 2 1]
 [2 2 1]
 [2 1 1]]
player1 wins!
